# PyTorch Overview & Examples

From section [PyTorch Overview (32.28)](https://www.youtube.com/watch?v=UU1WVnMk4E8&t=2008s) in tutorial.

In [1]:
import torch

### `torch.randint`

Using `torch.randint` let's us choose the range (first two numbers), `(min, max)` as well as how many random integers in the output, `(6,)`, for the **tensor** object.

In [2]:
randint = torch.randint(-100, 100, (6,))
randint

tensor([ 45, -89, -42, -97, -15,  66])

### `torch.tensor`

This sets up a tensor object, each sublist is a new row, sets up a matrix:

| | |
|---|---|
| 0.1 | 1.2 |
| 2.2 | 3.1 |
| 4.9 | 5.2 |

In [4]:
tensor = torch.tensor([[0.1, 1.2], [2.2, 3.1], [4.9, 5.2]])
tensor

tensor([[0.1000, 1.2000],
        [2.2000, 3.1000],
        [4.9000, 5.2000]])

### `torch.zeroes`

This defines an empty shape for a tensor. It defines the shape, made up of floats, by $\text{rows}\times \text{columns}$.

In [5]:
zeros = torch.zeros(2, 3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

### `torch.ones`

Same as zeros, define the shape, made up of float 1s.

In [7]:
ones = torch.ones(3, 5)
ones

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

### `torch.arange`

This creates a tensor object in a range, in this case `5`, which is `0`...`5`.

In [10]:
arange = torch.arange(5)
arange

tensor([0, 1, 2, 3, 4])

### `torch.linspace`

Similarly, this creates a range, in our case between `3` and `10`, calculating the difference between the numbers by the `step` size.

In [11]:
linspace = torch.linspace(3, 10, steps=5)
linspace

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])

Let's check what the constant increment is between them.

In [15]:
n1 = float(linspace[1])
n2 = float(linspace[0])
n1 - n2

1.75

### `torch.logspace`

This function differs in that it `start`s at $1^n$, `end`s at $1^n$, with automatically calculated `step`s defined. In our case, $1^{-10}$ to $1^{10}$ in `5` steps.

In [16]:
logspace = torch.logspace(start=-10, end=10, steps=5)
logspace

tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10])

### `torch.eye`

This creates a matrix where the value `1.0` is assigned to every next column and row and the shape is defined by the argument, in our case `5`.

| | | | | |
|---|---|---|---|---|
| 1.0 | | | | |
| | 1.0 | | | |
| | | 1.0 | | |
| | | | 1.0 | |
| | | | | 1.0 |

In [17]:
eye = torch.eye(5)
eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

### `torch.empty_like`

The main emphasis here is the datatype, in our case `dtype=torch.int64`. Instead of creating an empty of floating point values, we can define what datatype the tensor should include.

In [18]:
empty_like = torch.empty_like(torch.empty(2, 3), dtype=torch.int64)
empty_like

tensor([[0, 0, 0],
        [0, 0, 0]])

### CPU vs GPU (m1 (`mps`)) performance in `torch`

Let's compare the difference in speed between CPU and m1 on Mac, `mps`. First, let's set our device to `mps` and import some other libraries. We'll test `numpy` on the `cpu` and `torch` on the m1 `mps`.

In [21]:
import torch
import numpy as np
import time

device = torch.device("mps")
device

device(type='mps')

Let's measure `mps` time with this calculation. Again, we're mainly concerned with the iterative process time. Let's create a 10,000x10,000 tensor object of floating point numbers pushed to the m1 and do the same thing in `numpy`.

To multiply matrices in `torch`, we'll use the `@` symbol (line 8), and it'll give us a new random tensor. To multiply them in `numpy`, we use `np.multiply`. Let's compare.

In [24]:
torch_rand1 = torch.rand(10000, 10000).to(device)
torch_rand2 = torch.rand(10000, 10000).to(device)
np_rand1 = torch.rand(10000, 10000)
np_rand2 = torch.rand(10000, 10000)

start_time = time.time()

rand = (torch_rand1 @ torch_rand2)

end_time = time.time()

elapsed_time = end_time - start_time
print(f"m1 time: {elapsed_time: .8f}")

start_time = time.time()

rand = np.multiply(np_rand1, np_rand2)
end_time = time.time()
elapsed_time = end_time - start_time
print(f"cpu time: {elapsed_time: .8f}")

m1 time:  0.02777719
cpu time:  0.53274226


/var/folders/9v/bp828d7j3xn9rrsxwk7p7kjr0000gn/T/ipykernel_50046/1189135628.py:17: DeprecationWarning: __array_wrap__ must accept context and return_scalar arguments (positionally) in the future. (Deprecated NumPy 2.0)
  rand = np.multiply(np_rand1, np_rand2)


The difference isn't very big. The m1 is definitely faster, here, but not by a ton. The example in the video was `0.89495587` and `0.08935308`, so my CPU is definitely much slower. My m1 `mps` speed doesn't even match the much faster CPU on his computer.

The idea is that the CPU handles very quickly because there isn't much to do. Let's change the shape of the matrix and check again.

In [26]:
torch_rand1 = torch.rand(100, 100, 100, 100).to(device)
torch_rand2 = torch.rand(100, 100, 100, 100).to(device)
np_rand1 = torch.rand(100, 100, 100, 100)
np_rand2 = torch.rand(100, 100, 100, 100)

start_time = time.time()

rand = (torch_rand1 @ torch_rand2)

end_time = time.time()

elapsed_time = end_time - start_time
print(f"m1 time: {elapsed_time: .8f}")

start_time = time.time()

rand = np.multiply(np_rand1, np_rand2)
end_time = time.time()
elapsed_time = end_time - start_time
print(f"cpu time: {elapsed_time: .8f}")

m1 time:  0.02763176
cpu time:  0.09301782


/var/folders/9v/bp828d7j3xn9rrsxwk7p7kjr0000gn/T/ipykernel_50046/1315394993.py:17: DeprecationWarning: __array_wrap__ must accept context and return_scalar arguments (positionally) in the future. (Deprecated NumPy 2.0)
  rand = np.multiply(np_rand1, np_rand2)


It seems that running things a second time speeds it up for some reason, my first numbers were far worse than the ones above. A lot of simple tasks is what the m1 (GPU) thrives on, a single, more complex problem is where the CPU thrives.